# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='grades.Student'),
        ),
    ]
