# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('grades', '0002_auto_20170726_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='teacher_student', to='log_reg.User'),
        ),
    ]
